backend = "xrender";
vsync = true;
use-damage = true;
corner-radius = 0;
shadow = false;
fading = false;
frame-opacity = 1.0;
focus-exclude = [
  "class_g = 'dwm'",
  "class_g = 'Rofi'",
  "class_g = 'trayer'",
  "window_type = 'tooltip'",
  "window_type = 'popup_menu'",
  "window_type = 'dropdown_menu'"
];
wintypes:
{
  normal = { fade = true; shadow = true; };
  tooltip = { fade = true; shadow = false; opacity = 0.95; focus = true; full-shadow = false; corner-radius = 6; };
  dock = { shadow = false; clip-shadow-above = true; };
  dnd = { shadow = false; };
  popup_menu = { opacity = 1.0; shadow = false; corner-radius = 6; };
  dropdown_menu = { opacity = 1.0; shadow = false; corner-radius = 6; };
};
