local map = vim.keymap.set
map("n", "<C-a>", "ggVG", { desc = "Seleccionar todo el texto" })
map("i", "jk", "<Esc>", { desc = "Volver al modo normal" })
map({ "i", "n" }, "<esc>", "<cmd>noh<cr><esc>", { desc = "Escape y limpiar búsqueda" })
map("n", "<leader>h", "<cmd>nohlsearch<CR>", { desc = "Limpiar resaltado de búsqueda" })
map("n", "ss", "<cmd>split<CR>", { desc = "Split Horizontal" })
map("n", "sd", "<cmd>vsplit<CR>", { desc = "Split Vertical" })
map("n", "sq", "<cmd>q<CR>", { desc = "Cerrar Archivo" })
map("n", "<C-h>", "<C-w>h", { desc = "Ventana Izquierda" })
map("n", "<C-j>", "<C-w>j", { desc = "Ventana Abajo" })
map("n", "<C-k>", "<C-w>k", { desc = "Ventana Arriba" })
map("n", "<C-l>", "<C-w>l", { desc = "Ventana Derecha" })
map("n", "<S-h>", "<cmd>bprevious<CR>", { desc = "Buffer Anterior" })
map("n", "<S-l>", "<cmd>bnext<CR>", { desc = "Siguiente Buffer" })
map("v", "J", ":m '>+1<CR>gv=gv", { desc = "Mover bloque abajo" })
map("v", "K", ":m '<-2<CR>gv=gv", { desc = "Mover bloque arriba" })
map("v", "<", "<gv", { desc = "Quitar sangría y mantener selección" })
map("v", ">", ">gv", { desc = "Añadir sangría y mantener selección" })
map("v", "p", '"_dP', { desc = "Pegar sin sobrescribir el portapapeles" })
map("n", "<C-d>", "<C-d>zz", { desc = "Scroll abajo centrado" })
map("n", "<C-u>", "<C-u>zz", { desc = "Scroll arriba centrado" })
map("n", "n", "nzzzv", { desc = "Siguiente resultado de búsqueda centrado" })
map("n", "N", "Nzzzv", { desc = "Resultado anterior de búsqueda centrado" })
map("n", "<leader>cq", vim.diagnostic.setloclist, { desc = "Lista de diagnósticos en loclist" })
map("n", "bd", function()
	local ok, snacks = pcall(require, "snacks")
	if ok then
		snacks.bufdelete()
	else
		vim.cmd("bp | bd #")
	end
end, { desc = "Cerrar Buffer actual sin romper splits" })
